workflows:
  ios_testflight:
    name: ThreadLoop iOS (Capacitor → TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: "ThreadLoop API Key"

    environment:
      xcode: latest
      node: 18
      cocoapods: default
      vars:
        BUNDLE_ID: "com.threadloop.app"
        TEAM_ID: "ANYNJ42USZ"
        SCHEME: "App"
        WORKSPACE: "ios/App/App.xcworkspace"
        PROJECT_PATH: "ios/App"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.threadloop.app

    scripts:
      - name: Install Node deps
        script: npm ci || npm i

      - name: Build web assets
        script: npm run build

      - name: Add/sync iOS (Capacitor)
        script: |
          npx cap add ios || true
          npx cap sync ios

      - name: Install CocoaPods
        working_directory: ios/App
        script: pod install --repo-update

      - name: Ensure bundle id & team in Xcode project
        working_directory: ios/App
        script: |
          set -e
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]*;/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" App.xcodeproj/project.pbxproj
          sed -i '' "s/DEVELOPMENT_TEAM = [A-Z0-9]*/DEVELOPMENT_TEAM = $TEAM_ID/g" App.xcodeproj/project.pbxproj

      - name: Apply profiles
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          set -e
          xcode-project build-ipa --workspace "$WORKSPACE" --scheme "$SCHEME"
          FOUND_IPA="$(find "$CM_BUILD_DIR" -name '*.ipa' -print -quit || true)"
          [ -z "$FOUND_IPA" ] && FOUND_IPA="$(find . ios/App -name '*.ipa' -print -quit || true)"
          [ -n "$FOUND_IPA" ] && cp "$FOUND_IPA" "$CM_ARTIFACTS/" || (echo "No IPA found" && exit 2)
          ls -lah "$CM_ARTIFACTS" || true

    artifacts:
      - $CM_ARTIFACTS/*.ipa
      - /Users/builder/export_options.plist

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
