workflows:
  ios_testflight:
    name: ThreadLoop iOS (Capacitor → TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: "ThreadLoop API Key"

    environment:
      xcode: latest
      node: 18
      cocoapods: default
      vars:
        BUNDLE_ID: "com.threadloop.app"
        TEAM_ID: "WF7869BFQ2"
        SCHEME: "App"
        WORKSPACE: "ios/App/App.xcworkspace"
        PROJECT_PATH: "ios/App"

    scripts:
      - name: Install Node deps
        script: |
          npm ci || npm i

      - name: Build web assets
        script: |
          npm run build

      - name: Add/sync iOS (Capacitor)
        script: |
          npx cap add ios || true
          npx cap sync ios

      - name: Install CocoaPods
        working_directory: ios/App
        script: |
          pod install --repo-update

      - name: Set up signing (automatic via ASC)
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Archive
        script: |
          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -destination "generic/platform=iOS" \
            clean archive | xcpretty

      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportOptionsPlist /Users/builder/export_options.plist \
            -exportPath "$CM_ARTIFACTS" | xcpretty

    artifacts:
      - $CM_ARTIFACTS/*.ipa
      - build/**/*

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        # beta_groups:
        #   - Internal Testers
